### PR TITLE
Added 'confirm' event

### PR DESCRIPTION
**Pull request by DoctorMcKay**

### CODE REVIEW

**Comment by paralin** [comment]
+1

**Comment by unr** [comment]
:+1: @seishun Any reason this hasn't been merged? Would be useful!

**Comment by seishun** [comment]
My concern is that this isn't used by Valve's trading code, making it more likely that they will break or remove it at some point.

**Comment by DoctorMcKay** [comment]
It has existed in trading since 2011. I find it unlikely that they will remove it.

Even if they do, then we can just remove it as well. No problem there.

**Comment by seishun** [comment]
>Even if they do, then we can just remove it as well. No problem there.

It will be problem if people start relying on it.

**Comment by andrewda** [comment]
I agree that this would be a great feature.

> It will be problem if people start relying on it.

Then it might be a good idea to add something about that to the README. Something simple telling people that it's not officially supported by Valve so to not rely on it for their entire bot to function.

**Comment by unr** [comment]
Because of the missing `confirm` event on `node-steam-trade`, I ended up using [Trade Offer Manager](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager) instead.

**Comment by seishun** [comment]
@andrewda If you can't rely on it, then what's the point? What's your use case for it?

**Comment by DoctorMcKay** [comment]
It's reliable enough to include.

**Comment by andrewda** [comment]
What @DoctorMcKay said. In my opinion if it doesn't work it's Steam's fault, like oh so many other things. There will always be Steam issues, so as long as it's reliable **enough** I think it'll probably be a useful addition for most people.

**Comment by seishun** [comment]
I decided against this. I admit that the risk of this event stopping working is low, but its usefulness is also very low (human traders are doing just fine without it).

>In my opinion if it doesn't work it's Steam's fault, like oh so many other things.

In this case it would be my fault for relying on a hidden feature.

**Comment by DoctorMcKay** [comment]
It makes the trade appear more fluid on the human user's side, since the "Make Trade" button doesn't turn into a spinner if the other side has already confirmed. Making the bot confirm after the user does is a better UX.

Also, VoiDeD once wrote me a trade bot that used this "hidden feature", and I think he's a pretty good authority on Steam things.

**Comment by seishun** [comment]
>It makes the trade appear more fluid on the human user's side, since the "Make Trade" button doesn't turn into a spinner if the other side has already confirmed. Making the bot confirm after the user does is a better UX.

I'm not comfortable with the idea of relying on a hidden feature to work around Valve's bad UI.

>Also, VoiDeD once wrote me a trade bot that used this "hidden feature", and I think he's a pretty good authority on Steam things.

VoiDeD has been wrong on many Steam things, so your appeal to authority is misplaced.

**Comment by DoctorMcKay** [comment]
>its usefulness is also very low (human traders are doing just fine without it).

I gave you an example of usefulness, and now your talking about how you're uncomfortable with how people are running their bots?

**Pull request closed without merging**
